---
kind: Cluster  # cluster config
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # By default the API server can be accessed from local machine.
  # The API server port is mapped to a random port on the host machine.
  apiServerAddress: "127.0.0.1"
nodes:
- role: control-plane
  image: kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518
  extraPortMappings:
  - containerPort: 30950  # The port exposed by the node.
    hostPort: 30950  # The port on the host machine.
  - containerPort: 30001
    hostPort: 30001
  extraMounts:
  - hostPath: ./volumes/control-plane
    containerPath: /volume
- role: worker
  image: kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518
- role: worker
  image: kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518
- role: worker
  image: kindest/node:v1.27.0@sha256:c6b22e613523b1af67d4bc8a0c38a4c3ea3a2b8fbc5b367ae36345c9cb844518
